#!/usr/bin/env bash
appendpath () {
    case ":$PATH:" in
        *:"$1":*) ;;
        *) export PATH="$PATH:$1"
    esac
}

for p in /sbin /usr/local/go/bin /usr/local/bin /usr/local/sbin \
               $HOME/bin $HOME/.local/bin $HOME/.cargo/bin/; do
    appendpath $p
done

export DEFAULT_USER=i1i1
export GIT_CONFIG=$RCFG_DIR/gitconfig
export LC_ALL=en_US.utf8
export TERM=xterm-256color

eval `dircolors $BASHDOTDIR/dircolors`

source $BASHDOTDIR/aliases
source $BASHDOTDIR/functions
source $BASHDOTDIR/prompt

which fzf &>/dev/null && source $BASHDOTDIR/autocompletion/fzf.bash

for file in $(ls $BASHDOTDIR/autocompletion | grep -v fzf); do
    source $BASHDOTDIR/autocompletion/$file
done
