#!/usr/bin/env bash
appendpath () {
    case ":$PATH:" in
        *:"$1":*) ;;
        *) export PATH="$PATH:$1"
    esac
}
have() {
    unset -v have
    # Completions for system administrator commands are installed as well in
    # case completion is attempted via `sudo command ...'.
    PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin type $1 &>/dev/null &&
    have="yes"
}

for p in /sbin /usr/local/go/bin /usr/local/bin /usr/local/sbin \
               $HOME/bin $HOME/.local/bin $HOME/.cargo/bin/; do
    appendpath $p
done

export DEFAULT_USER=i1i1
export GIT_CONFIG=$RCFG_DIR/gitconfig
export LC_ALL=en_US.utf8
export TERM=xterm-256color

eval `dircolors $BASHDOTDIR/dircolors`

TO_SOURCE=( $BASHDOTDIR/autocompletion/* )
if [ -r /etc/bash_completion ]; then
    TO_SOURCE=( ${TO_SOURCE[@]} /etc/bash_completion )
else
    TO_SOURCE=( ${TO_SOURCE[@]} /usr/share/bash-completion/*/* )
fi
if ! (which fzf &>/dev/null && fzf -h &>/dev/null); then
    TO_SOURCE=( $(echo ${TO_SOURCE[@]} | tr ' ' '\n' | grep -v fzf) )
fi
TO_SOURCE=( ${TO_SOURCE[@]} $BASHDOTDIR/{aliases,functions,prompt} )

for file in "${TO_SOURCE[@]}"; do
    source $file
done

