#!/usr/bin/env bash
is_installed() {
    which $* &>/dev/null
}
get_os() {
    awk -F= '/^ID=/{print $2}' /etc/os-release
}
install_packets_os() {
    install=0
    for p in $*; do
        is_installed $p && continue
        install=1
    done

    [ $install = 0 ] && return

    case $(get_os) in
        arch)              sudo pacman -S --confirm $* ;;
        raspbian|debian|ubuntu) sudo apt install -y $* ;;
    esac
}
install_packets_special() {
    for p in $*; do
        is_installed $p && continue
        install_$p
    done
}
install_fzf() {
    is_installed fzf && return

    git clone --depth 1 https://github.com/junegunn/fzf.git /tmp/fzf
    yes n | /tmp/fzf/install &>/dev/null
    sudo cp /tmp/fzf/bin/fzf /usr/bin
    sudo rm -r ~/.fzf.bash /tmp/fzf
}
install_ripgrep() {
    is_installed rg && return

    if [ $(uname -m) = x86_64 ]; then
        URL=https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep-11.0.2-x86_64-unknown-linux-musl.tar.gz
    else
        URL=https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep-11.0.2-arm-unknown-linux-gnueabihf.tar.gz
    fi

    (
        cd /tmp
        wget -O - $URL | tar zxf -
        sudo cp ripgrep-*/rg /usr/bin/
        rm -r ripgrep-*/
    )
}
install_exa() {
    is_installed exa && return

    case $(get_os) in
        arch)          install_packets_os exa ;;
        debian|ubuntu)
            [ $(uname -m) != x86_64 ] && return

            ZIP=$(mktemp --suffix zip -u)
            URL=https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
            curl -o $ZIP -L $URL
            unzip $ZIP
            sudo mv exa* /usr/bin/exa
            rm $ZIP
            ;;
    esac
}


install_packets_os \
    curl \
    git \
    nmap \
    rsync \
    sshfs \
    tmux \
    unzip

install_packets_special \
    exa \
    fzf \
    ripgrep
