#!/usr/bin/env bash
get_os() { (. /etc/os-release; echo $ID); }
install_packets_os() {
    install=0
    for p in $*; do
        is_installed $p && continue
        install=1
    done

    [ $install = 0 ] && return

    case $(get_os) in
        arch)                   pacman -S --confirm $* ;;
        raspbian|debian|ubuntu)
            apt-get update --fix-missing
            apt install -y $*
            ;;
    esac
}

install_packets_os \
    curl \
    git \
    nmap \
    rsync \
    sshfs \
    tmux \
    unzip \
    zip \
    zsh
