#!/usr/bin/env bash
is_installed() {
    which $* &>/dev/null
}
get_os() {
    awk -F= '/^ID=/{print $2}' /etc/os-release
}
install_packets_os() {
    install=0
    for p in $*; do
        is_installed $p && continue
        install=1
        break
    done

    [ $install = 0 ] && return

    case $(get_os) in
        arch)                   $SUDO pacman -S --confirm $* ;;
        raspbian|debian|ubuntu) $SUDO apt install -y $* ;;
    esac
}

install_deps() {
	[ $(id -u) != 0 ] && SUDO=sudo
	install_packets_os \
		  curl \
		  git \
		  nmap \
		  rsync \
		  tmux \
		  unzip \
		  zip \
		  zsh
}

install_deps
exec bash --rcfile ~/.sh/i1i1/runcfg
