#!/usr/bin/env bash
is_installed() {
    which $* &>/dev/null
}
get_os() {
    awk -F= '/^ID=/{print $2}' /etc/os-release
}
install_packets_os() {
    install=0
    for p in $*; do
        is_installed $p && continue
        install=1
    done

    [ $install = 0 ] && return

    case $(get_os) in
        arch)              sudo pacman -S --confirm $* ;;
        raspbian|debian|ubuntu) sudo apt install -y $* ;;
    esac
}
install_packets_special() {
    for p in $*; do
        is_installed $p && continue
        install_$p
    done
}
install_fzf() {
    is_installed fzf && return

    case $(get_os) in
        arch)          install_packets_os fzf ;;
        raspbian) ;;
        debian|ubuntu)
            [ $(uname -m) != x86_64 ] && return
            (
                cd /usr/bin/
                curl -L https://github.com/junegunn/fzf-bin/releases/download/0.20.0/fzf-0.20.0-linux_amd64.tgz | \
                    sudo tar -xz -f -
            )
            ;;
    esac
}
install_ripgrep() {
    is_installed rg && return

    case $(get_os) in
        arch)          install_packets_os ripgrep ;;
        raspbian) ;;
        debian|ubuntu)
            [ $(uname -m) != x86_64 ] && return

            DEB=$(mktemp --suffix deb -u)
            URL=https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
            curl -o $DEB -L $URL
            sudo dpkg -i $DEB
            rm $DEB
            ;;
    esac
}
install_exa() {
    is_installed exa && return

    case $(get_os) in
        arch)          install_packets_os exa ;;
        raspbian) ;;
        debian|ubuntu)
            [ $(uname -m) != x86_64 ] && return

            ZIP=$(mktemp --suffix zip -u)
            URL=https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
            curl -o $ZIP -L $URL
            unzip $ZIP
            sudo mv exa* /usr/bin/exa
            rm $ZIP
            ;;
    esac
}

install_packets_os \
    curl \
    git \
    nmap \
    rsync \
    sshfs \
    unzip

install_packets_special \
    exa \
    fzf \
    ripgrep

export BASHDOTDIR=$RCFG_DIR
exec bash --rcfile $RCFG_DIR/bashrc
