appendpath () {
    case ":$PATH:" in
        *:"$1":*) ;;
        *) export PATH="$PATH:$1"
    esac
}


# General
for p in /sbin /usr/local/go/bin /usr/local/bin /usr/local/sbin \
               $HOME/bin $HOME/.local/bin $HOME/.cargo/bin/; do
    appendpath $p
done

export LC_ALL=en_US.utf8
export IFS='\n'

# ZSH
export ZSH="$ZDOTDIR/.oh-my-zsh"
export ZSH_THEME=crunch
export UPDATE_ZSH_DAYS=7
export ENABLE_CORRECTION=true
export COMPLETION_WAITING_DOTS=true
export plugins=(git fzf)


source $ZSH/oh-my-zsh.sh
source $ZDOTDIR/zaliases
source $ZDOTDIR/zfunctions
